### ISSUE TITLE
footmisc v6 handles the bottom option incorrectly in some cases

### ISSUE THREAD

**Issue by akiyks** [FrankMittelbach/fmitex-footmisc#1]
Hi,

I tried v6 of footmisc and noticed the changes described in section 1.8.4. of footmisc-doc.pdf.
It says "LaTeX shows a somewhat strange discrepancy," but I think the behavior is preferable in twocolumn papers as it gives pages exactly flush-bottom.

I'd like to have an option to disable the "fix" in twocolumn layout, if it is not hard to implement.
Thoughts?

Thanks, Akira

**Comment by FrankMittelbach** [comment]
@akiyks Akirasan, in which combination do you think it is preferable? Can you give me the exact combination you are looking for (besides twocolumn)?

 - setting `\raggedbottom`or `\flushbottom`
 - footnotes  above or below bottom floats
 - excess space distributed where?

**Comment by FrankMittelbach** [comment]
Well, the v5 behavior of bottom was also very odd with `\flushbottom`:

 - text + b-float + footnotes   =   text, b-floats closely attached, excess space, footnotes at bottom
 - text + b-floats no footnotes = text, excess space b-floats at bottom
 - text + footnotes no bfloats = text, excess space, footnotes at bottom

you really want the first line of the behavior back? because except for that this, getting excess space above footnotes would be "bottomfootnotes".

In my opinion the behavior had a bug with respect to the first line it shouldd have pushed the excess space *always* above floats not only sometimes, but I could make it come back and apply the fix only if you say "abovefloats" or "belowfloats".

**Comment by akiyks** [comment]
Well, what I'd like to restore is the exact flush-bottom behavior.
I don't mind if extra vertical spaces are somewhat different from v5.x, if flush-bottom works as expected.
Maybe I'm too accustomed to the v5.5 behavior, but the first line of the behavior does not look so strange to me.

And I'd like to have my LaTeX code portable with both v5.5 and v6.x.
Actually it is not a personal project but an open-source textbook.
So "only if I say "abovefloats" or "belowfloats"" wouldn't work for me.

Am I asking something unreasonable to you?

**Comment by FrankMittelbach** [comment]
> Well, what I'd like to restore is the exact flush-bottom behavior. I don't mind if extra vertical spaces are somewhat different from v5.x, if flush-bottom works as expected. Maybe I'm too accustomed to the v5.5 behavior, but the first line of the behavior does not look so strange to me.

well, it does to me if you compare it to the second line. why should your float move from close to text to the bottom just because you add a footnote?

> And I'd like to have my LaTeX code portable with both v5.5 and v6.x. Actually it is not a personal project but an open-source textbook. So "only if I say "abovefloats" or "belowfloats"" wouldn't work for me.

sorry, what would not work for you when?

> 
> Am I asking something unreasonable to you?

No, not at all unreasonable. I am just trying to understand what the exact behavior is you are looking for.
There are different possibilities how to handle things, from offering some option like "no-newpage-fix" to make "bottom" behave buggy as it did before,  ...

Right now without any modification, what you can do is
```
\usepackage[bottom]{footmisc}[=v5]
```

The problem with bugs fixes only offered by opt-in is that most of the time people don't know there is something to opt in to get corrected behavior, which is why I tend to providing an opt out

**Comment by akiyks** [comment]
Let's talk with a screenshot.  Attached is a bottom of a page in twocolumn layout typeset with \flushbottom and \usepackage[bottom]{footmisc} (v6.0a).

![footmisc-v6a-flushbottom-with-bottom-option](https://user-images.githubusercontent.com/19179118/153750125-90505433-4f77-46da-aff9-2abac71a3fa9.png)

I think this looks strange.  Note that this page does not have any float.

**Comment by akiyks** [comment]
I will prepare a MWE for this issue.
Please wait a day or so.
Thanks!

**Comment by FrankMittelbach** [comment]
couple of comments on your picture:

 - this is what you get from `\flushbottom` without any package loaded. So why is that suprising when `\usepackage[bottom]{footmisc}` comes along?
 - this behavior is the same in v5 and v6 (unless I'm totally mistaken)
 - I agree that it doesn't look beautiful in this particular case, but consistent: the ask is for flush bottom and you get a flush bottom

**Comment by FrankMittelbach** [comment]
Actually it does not conflict with this package, the footmisc update simply has a bug :-( and using this package happened to show it. I'm currently rewriting the logic as I messed up some important subcases. That should bring the  behavior back. Give me a day ...

**Comment by FrankMittelbach** [comment]
@akiyks I think that I got the logic now right, but before uploading to CTAN, perhaps you want to do a quick check with the version now in the repo?

**Comment by akiyks** [comment]
Got it!  Will test it soon.

**Comment by akiyks** [comment]
v6.0b works  fine.
To make sure I actually tested v6.0b, here is an excerpt from .log:

```
(./footmisc.sty
Package: footmisc 2022/02/14 v6.0b a miscellany of footnote facilities
```

**Comment by FrankMittelbach** [comment]
uploaded to CTAN
